services:
  manager-app:
    build:
      context: .
      dockerfile: manager_app/Dockerfile
    container_name: revature-expense-manager
    ports:
      - "8080:8080"
    volumes:
      - ./db:/app/db
    restart: unless-stopped
  employee-app:
    build:
      context: ./employee_app
    container_name: employee-app
    ports:
      - "5001:5000"
    volumes:
      - ./db:/db
